baseURL: /acme
languageCode: es-es
title: ACME Servicios
theme: Eclectic
author: 
  facebook: "https://facebook.com/ACME" 
  twitter: "https://twitter.com/ACME" 
  email: "contact@example.org" 
  name: "Acme Empresa" 
  location: Soria
  phone: (999) 123-7890 
  hours: "**Lunes-Jueves** 9:00AM - 6:00PM" 

menu:
  main: 
    - identifier: Acerca de
      name: About 
      url: /about 
      weight: 100  
    - identifier: contact
      name: Contacto 
      url: /contacto 
      weight: 200
    - identifier: curriculum
      name: Curriculum 
      url: /curriculum 
      weight: 50  
    - identifier: Viajes
      name: viajes 
      url: /viajes 
      weight: 40 
params: 
  colorPickerEnabled: true 
  color: "#2d48e7"
  copyright: "Copyright &copy; 2022 Acme Corporation. Todos los derechos reservados."
  footer:
  - title: About
    content: >
      Acme Corporation is the world's leading
      manufacturer of digital shapes. From squares and
      circles to triangles and hexagons, we have it
      all. Browse through our collection of various
      forms with different thicknesses and line styles.
      We shape the world. You live in it.      


  - title: Publicaciones recientes
    recents: blog
    recentCount: 7

  - title: Contacta con nosotros
    contact: true